name: Publish SvelteKit bundle

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-sveltekit-bundle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.0

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.0.0
      with:
        node-version: 16.x

    - name: Install the dependencies
      run: |
        npm install

    - name: Build the bundle
      if: contains(github.ref, 'main')
      run: |
        npm run build
